jogae/app_chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('<str:username>/', views.chat_room, name='room'),
]

jogae/app_profile/urls.py
from django.urls import path

from . import views

app_name = "profile"
urlpatterns = [
    path("editProfile/", views.EditProfile, name="editProfile"),
    path("friends/", views.Friends, name="friends"),
    path("solicitacoes/", views.Solicitacoes, name="solicitacoes"),
    path("<str:pk>/addFriend/", views.AddFriend, name="addFriend"),
    path("<str:pk>/games/", views.games, name="games"),
    path("<str:pk>/", views.Profile, name="profile"),
]

jogae/games/urls.py
from django.urls import path

from . import views

app_name = "games"
urlpatterns = [
    path("", views.indexView, name="index"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<uuid:pk>/", views.DetailView.as_view(), name="detail"),
]

jogae/jogae/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from games.views import IndexView

from games import views as games_views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('cadastro_usuario/', include('app_cadastro_usuario.urls')),
    #path('', IndexView.as_view(), name='home'),
    #path('', include('games.urls')),
    
    path('', games_views.indexView, name='home'),

    path('games/', include("games.urls")),
    path('accounts/', include("app_cadastro_usuario.urls")),
    path('biblioteca/', include("app_biblioteca.urls")),
    path('profile/', include("app_profile.urls")),
    path('chat/', include('app_chat.urls')),
]

# This is only for development and should not be used in production
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

jogae/games/models.py
import uuid
from django.urls import reverse
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Avg

class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Game(models.Model):
    user = models.ForeignKey("app_cadastro_usuario.User", on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    description = models.TextField()
    picture = models.ImageField(upload_to="games/", null=True, blank=True)
    genres = models.ManyToManyField(Genre, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)

    def get_absolute_url(self):
        return reverse("games:detail", kwargs={"pk": self.id})

    def average_rating(self):
        return self.ratings.aggregate(Avg('rating'))['rating__avg'] or 0

    def __str__(self):
        return self.title

class Rating(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='ratings')
    user = models.ForeignKey("app_cadastro_usuario.User", on_delete=models.CASCADE, related_name='ratings')
    body = models.TextField(blank=True)
    rating = models.FloatField(
        validators = [MinValueValidator(0.0), MaxValueValidator(5.0)]
    )
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]


class GameTFIDF(models.Model):
    tfidf_matrix = models.BinaryField()  
    game_index_map = models.JSONField()  
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"TF-IDF Matrix (Created: {self.created_at})"

jogae/app_profile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages
from app_cadastro_usuario.forms import UserChangeForm
from django.db.models import Q, Count
from .models import Friendship
from app_biblioteca.models import FavoriteGamesByUser
from games.models import Game

User = get_user_model()

# Create your views here.

@login_required
def Profile(request,pk):

    user = get_object_or_404(User, username=pk)

    friendship_status = None
    if user != request.user:
        friendship = Friendship.objects.filter(
            (Q(from_user=request.user, to_user=user) | Q(from_user=user, to_user=request.user))
        ).first()

        if not friendship or friendship.status == Friendship.Status.DECLINED:
            friendship_status = 'NOT_FRIENDS'
        elif friendship.status == Friendship.Status.PENDING:
            friendship_status = 'PENDING'
        elif friendship.status == Friendship.Status.ACCEPTED:
            friendship_status = 'FRIENDS'

    context = { 
        'user' : user,
        'friendship_status': friendship_status
    }

    return render(request, 'profile/profile.html', context)

@login_required
def games(request,pk):
    
    user = get_object_or_404(User,username=pk)

    games = Game.objects.filter(user=user).annotate(
        save_count=Count('savedInLibrary')
    ).order_by('-save_count')

    context = {
        'user' : user,
        'games' : games
    }

    return render(request, 'profile/games.html', context)

@login_required
def Friends(request):
    # Use the manager to get a list of friend user objects
    friends = Friendship.objects.get_friends(request.user)

    # Get pending requests sent to the current user for them to accept/decline
    pending_requests = Friendship.objects.filter(to_user=request.user, status=Friendship.Status.PENDING)

    context = {
        'friends': friends,
        'pending_requests': pending_requests
    }

    return render(request, 'profile/friends.html', context)

@login_required
def EditProfile(request):
    if request.method == 'POST':
        form = UserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Seu perfil foi atualizado com sucesso!')
            return redirect('profile:profile', pk=request.user.username)
    else:
        form = UserChangeForm(instance=request.user)

    context = {
        'form': form
    }
    return render(request, 'profile/editProfile.html', context)

@login_required
def AddFriend(request, pk):

    to_user = get_object_or_404(User, username=pk)
    from_user = request.user

    if to_user == from_user:
        messages.error(request, "Você não pode adicionar a si mesmo como amigo.")
        return redirect('profile:profile', pk=to_user.username)

    
    existing_friendship = Friendship.objects.filter(
        (Q(from_user=from_user, to_user=to_user) | Q(from_user=to_user, to_user=from_user))
    ).first()

    if not existing_friendship:
        Friendship.objects.create(from_user=from_user, to_user=to_user)
        messages.success(request, f"Pedido de amizade enviado para {to_user.username}.")
    elif existing_friendship.status == Friendship.Status.DECLINED:
        # Se tiver sido recusado, pode ser feito novas tentativas de solicitação de amizade
        existing_friendship.from_user = from_user
        existing_friendship.to_user = to_user
        existing_friendship.status = Friendship.Status.PENDING
        existing_friendship.save()
        messages.success(request, f"Pedido de amizade enviado para {to_user.username}.")
    elif existing_friendship.status == Friendship.Status.PENDING:
        messages.info(request, f"Um pedido de amizade para {to_user.username} já está pendente.")
    elif existing_friendship.status == Friendship.Status.ACCEPTED:
        messages.info(request, f"Você já é amigo de {to_user.username}.")
    
    return redirect('profile:profile', pk=to_user.username)

@login_required
def Solicitacoes(request):
    user = request.user

    if request.method == 'POST':
        solicitacao_id = request.POST.get('solicitacao_id')
        # Ensure the request is for the logged-in user to prevent others from acting on their behalf
        friend_request = get_object_or_404(Friendship, id=solicitacao_id, to_user=user)

        if 'accept' in request.POST:
            friend_request.status = Friendship.Status.ACCEPTED
            friend_request.save()
            messages.success(request, f"Você e {friend_request.from_user.username} agora são amigos.")
        elif 'reject' in request.POST:
            friend_request.status = Friendship.Status.DECLINED
            friend_request.save()
            messages.info(request, f"Você rejeitou o pedido de amizade de {friend_request.from_user.username}.")
        
        return redirect('profile:solicitacoes')

    pending_requests = Friendship.objects.filter(to_user=user, status=Friendship.Status.PENDING)

    context = {
        'pending_requests': pending_requests
    }

    return render(request, 'profile/solicitacoes.html', context)

jogae/games/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg, F
from django.shortcuts import redirect, render

from .models import Game
from .forms import GameForm, RatingForm

from .recommendation_utils import (
    get_content_based_recommendations,
    get_collaborative_recommendations,
    get_friend_based_recommendations,
    get_content_based_rating,
    filter_by_similarity
)

""" class IndexView(generic.ListView):
    template_name = "games/index.html"
    context_object_name = "popular_games"

    def get_queryset(self):
        return Game.objects.annotate(avg_rating=Avg('ratings__rating')).order_by("-avg_rating")[:10]
        return Game.objects.order_by("rating")[:10] """

def indexView(request):
    user = request.user
    search_query = request.GET.get('q', '')
    sort_param = request.GET.get('orderby', None)
    
    # games_queryset para quando possui algum dado de busca ou ordenação
    games_queryset = None
    # games_list_with_scores para coletar os jogos recomendados e seu score de similaridade
    games_list_with_scores = []

    # se possuir alguma busca coleta jogos que atingem o item buscado
    if search_query:
        games_queryset = Game.objects.filter(title__icontains=search_query)
    else:
        # Caso não possuir busca efetua processo de recomendação
        
        # View padrão, para usuários que não estão autentificados ou não possuem jogos favoritos 
        if not user.is_authenticated or not hasattr(user, 'favoritegamesbyuser') or not user.favoritegamesbyuser.games.exists():
            games_queryset = Game.objects.annotate(avg_rating=Avg('ratings__rating')).order_by("-avg_rating")
        else:
            # View personalizada para aqueles que estão logados e possuem jogos favoritos
            user_favorites = list(user.favoritegamesbyuser.games.all())

            # Coleta as recomendações baseada em:
            # conteúdo comparado com os jogos favoritos | coletando também o gosto do usuário
            content_recs, user_profile = get_content_based_recommendations(user_favorites, return_profile=True)
            # usuários com gostos similares
            collab_recs = get_collaborative_recommendations(user)
            # amigos
            friend_recs = get_friend_based_recommendations(user)
            # conteúdo dos jogos com maiores ratings 
            rating_recs = get_content_based_rating(user, num_recommendations=5, return_profile=False)
            
            # Combina as recomendações
            combined_recs = rating_recs + content_recs + friend_recs + collab_recs

            final_recommendations = []
            # Coleta jogos que estejam nos jogos favoritos do usuário
            seen_pks = {game.pk for game in user_favorites}

            # Adiciona jogos a lista final que não estejam na lista de favoritos 
            for game in combined_recs:
                if game.pk not in seen_pks:
                    final_recommendations.append(game)
                    seen_pks.add(game.pk)


            # Se foi coletado o perfil do usuário filtra dentre todos os jogos que foram coletados recomendados
            # os 10 que possuem a maior similaridade com o gosto do usuário
            if user_profile is not None:
                # retorna uma tupla de (jogo, score de similaridade)
                games_list_with_scores = filter_by_similarity(user_profile, final_recommendations, num_recommendations=len(final_recommendations))
            else:
                # Se não possui o gosto do usuário retorna uma tupla de (jogos, score nulo)
                games_list_with_scores = [(game, None) for game in final_recommendations]

            # Se ainda não tiver os 10 jogos, completa com jogos populares
            if len(games_list_with_scores) < 10:
                needed = 10 - len(games_list_with_scores)
                # coleta jogos que foram colocados na lista dos mais recomendados
                current_pks = {game.pk for game, score in games_list_with_scores}
                seen_pks.update(current_pks)
                # pega os melhores jogos por rating e retira os jogos que ja foram colocados
                filler_games = Game.objects.annotate(
                    avg_rating=Avg('ratings__rating')
                ).exclude(pk__in=seen_pks).order_by('-avg_rating')[:needed]
                games_list_with_scores.extend([(game, None) for game in filler_games])

    # Aplica os parâmetros de organização
    if sort_param:
        if games_queryset is not None:
            if sort_param == 'title':
                games_queryset = games_queryset.order_by('title')
            elif sort_param == 'rating':
                games_queryset = games_queryset.annotate(avg_rating=Avg('ratings__rating')).order_by('-avg_rating')
        else:
            if sort_param == 'title':
                games_list_with_scores = sorted(games_list_with_scores, key=lambda item: item[0].title)
            elif sort_param == 'rating':

                # dicionário de jogos
                score_map = {game.id: score for game, score in games_list_with_scores}
                # coletando somente os ids dos jogos
                game_ids = list(score_map.keys())
                # fazendo uma filtragem pelos jogos mais bem avaliados 
                games_with_ratings = Game.objects.filter(pk__in=game_ids).annotate(
                    avg_rating=Avg('ratings__rating')
                ).order_by('-avg_rating')
                # Recolocando jogos na nova ordem
                games_list_with_scores = [(game, score_map.get(game.id)) for game in games_with_ratings]

    # Preparando o contexto
    if games_queryset is not None:
        final_list = [(game, None) for game in games_queryset[:10]]
    else:
        final_list = games_list_with_scores[:10]

    context = {
        'popular_games': final_list,
        'search_query': search_query,
    }
    
    return render(request, 'games/index.html', context)


class DetailView(generic.DetailView):
    model = Game
    template_name = "games/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        game = self.get_object()

        ordering = self.request.GET.get('orderby', 'recentes') 

        if ordering == 'recentes':
            context['ratings'] = game.ratings.order_by('-created')

        if ordering == 'rating':
            context['ratings'] = game.ratings.order_by('-rating')

        if self.request.user.is_authenticated:
            context['rating_form'] = RatingForm()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')

        self.object = self.get_object()
        form = RatingForm(request.POST)
        
        if form.is_valid():
            rating = form.save(commit=False)
            rating.game = self.object
            rating.user = request.user
            rating.save()
            return redirect(self.object.get_absolute_url())
        else:
            context = self.get_context_data()
            context['rating_form'] = form
            return self.render_to_response(context)

class CreateView(LoginRequiredMixin, generic.CreateView):
    model = Game
    """ fields = [
        'title',
        'description',
        'picture',
        'genres',
        'tags'
    ] """
    form_class = GameForm
    template_name = "games/create.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

jogae/app_profile/templates/profile/editProfile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editar Perfil{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/app_profile/profile.css' %}">
{% endblock %}

{% block content %}
<div class="edit-profile-container">
    <a href="{% url 'profile:profile' request.user.username %}" class="btn btn-back">Voltar ao Perfil</a>

    <h2>Editar Perfil</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar Alterações</button>
    </form>
</div>
{% endblock %}

jogae/app_profile/templates/profile/friends.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Meus Amigos{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/app_profile/profile.css' %}">
{% endblock %}

{% block content %}
<div class="friends-container">
    <a href="{% url 'profile:profile' request.user.username %}" class="btn btn-back">Voltar ao Perfil</a>

    <h2>Meus Amigos</h2>

    {% if friends %}
        {% for friend in friends %}
        <div class="friend-card">
            <div class="profile-header">
                <img src="{% static 'img/default_profile.png' %}" alt="Foto de Perfil" class="profile-picture">
                <a href="{% url 'profile:profile' friend.username %}" style="text-decoration:none; color:white;">
                    <h1>{{ friend.username }}</h1>
                </a>
            </div>
            <h3>Jogos feitos por @{{ friend.username }}</h3>
            <div class="friend-games-list">
                {% for game in friend.game_set.all %}
                <div class="game-single">
                    <div class="game-single__image">
                        {% if game.picture %}
                            <img src="{{game.picture.url}}" alt="{{ game.title }} cover" class="game-single__img">
                        {% else %}
                             <p>Sem foto :(</p>
                        {% endif %}
                    </div>
                    <div class="game-single__info">
                        <h2 class="game-single__title">{{ game.title }}</h2>
                        <div class="game-single__buttons">
                            <a href="{% url 'games:detail' game.id %}" class="btn btn-secondary">Visualizar</a>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p>Nenhum jogo criado por este usuário.</p>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    {% else %}
        <p style="text-align: center; font-size: 1.2rem;">Você ainda não tem amigos. :(</p>
    {% endif %}
</div>
{% endblock %}

jogae/app_profile/templates/profile/games.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Meus jogos{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/app_profile/profile.css' %}">
{% endblock %}

{% block content %}
<div class="user-games-container">
    <a href="{% url 'profile:profile' user.username %}" class="btn btn-back">Voltar ao Perfil</a>

    <h2>Jogos de {{ user.username }}</h2>

    {% for game in games %}
    <div class="game-single">
        <div class="game-single__image">
            {% if game.picture %}
                <img src="{{game.picture.url}}" alt="{{ game.title }} cover" class="game-single__img">
            {% else %}
                <div class="no-photo" style="width: 15rem; height: 15rem;"><p>Sem foto :(</p></div>
            {% endif %}
        </div>
        <div class="game-single__info">
            <div class="game-single__td">
                <h2 class="game-single__title">{{ game.title }}</h2>
                <div class="game-single-stats">
                    <p><strong>Rating:</strong> {{game.average_rating|floatformat:1}} / 5.0</p>
                    <p><strong>Salvo:</strong> {{ game.save_count }} vezes</p>
                </div>
                <p class="game-single__desc">{{ game.description|truncatewords:40 }}</p>
            </div>
            <div class="game-single__buttons">
                <a href="{% url 'games:detail' game.id %}" class="btn btn-primary">Visualizar</a>
            </div>
        </div>
    </div>
    {% empty %}
    <p style="text-align: center; font-size: 1.2rem;">{{ user.username }} ainda não criou nenhum jogo.</p>
    {% endfor %}
</div>
{% endblock %}

jogae/app_profile/templates/profile/myGames.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Meus jogos{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/app_profile/profile.css' %}">
{% endblock %}


{% block content %}
<div class="profile-container">
    <a href="{% url 'profile:profile' %}">Voltar</a>


    <h2>Meus jogos</h2>
    
    {% for game in games %}

    <div class="game-single">
        <div class="game-single__image">
          {% if game.picture %}
          <img src="{{game.picture.url}}" alt="{{ game.title }} cover" class="game-single__img">
          {% else %}
          <p>Sem foto :(</p>
          {% endif %}
        </div>
        <div class="game-single__info">
          <div class="game-single__td">
            <h2 class="game-single__title">{{ game.title }}</h2>
            <p class="game-single__desc">{{ game.description }}</p>
          </div>
          <div class="game-single__buttons">
            <a href="{% url 'games:detail' game.id %}" class="btn">Visualizar</a>
          </div>
        </div>
      </div>

    {% endfor %}
    
</div>
{% endblock %}

jogae/app_profile/templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Perfil de {{ user.username }}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/app_profile/profile.css' %}">
{% endblock %}


{% block content %}
<div class="profile-container">
    <div class="profile-header">
        <img src="{% static 'img/default_profile.png' %}" alt="Foto de Perfil" class="profile-picture">
        <h1>{{ user.username }}</h1>
        {% if friendship_status == 'FRIENDS' %}
            <span class="friend-badge" style="cursor: default;">Amigos</span>
        {% endif %}
        <p class="profile-email">{{ user.email }}</p>
    </div>

    <div class="profile-details">
        <h2>Bio:</h2>
        <p>{{ user.bio|default:"Nenhuma biografia informada."|linebreaksbr }}</p>
    </div>

    <div class="profile-actions">
        {% if user == request.user %}
            <a href="{% url 'profile:editProfile' %}" class="btn btn-primary">Editar Perfil</a>
            <a href="{% url 'profile:friends' %}" class="btn btn-secondary">Amigos</a>
            <a href="{% url 'profile:solicitacoes' %}" class="btn btn-secondary">Solicitações de Amizade</a>
        {% else %}
        {% if friendship_status == 'NOT_FRIENDS' %}
        <a href="{% url 'profile:addFriend' user.username %}" class="btn btn-secondary">Adicionar Amigo</a>
        {% elif friendship_status == 'PENDING' %}
        <span class="btn btn-secondary">Pedido Pendente...</span>
        {% elif friendship_status == 'FRIENDS' %}
                <a href="{% url 'chat:room' user.username %}">CHAT</a>
            {% endif %}
        {% endif %}
        <a href="{% url 'profile:games' user.username %}" class="btn btn-secondary">Jogos</a>
    </div>

</div>
{% endblock %}

jogae/app_profile/templates/profile/solicitacoes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Solicitações de Amizade{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/app_profile/profile.css' %}">
{% endblock %}

{% block content %}
<div class="requests-container">
    <a href="{% url 'profile:profile' request.user.username %}" class="btn btn-back">Voltar ao Perfil</a>

    <h2>Solicitações de Amizade</h2>

    {% for solicitacao in pending_requests %}
        <div class="request-item">
            <p><a href="{% url 'profile:profile' solicitacao.from_user.username %}">{{solicitacao.from_user.username}}</a> quer ser seu amigo.</p>
            <form method="POST" action="{% url 'profile:solicitacoes' %}">
                {% csrf_token %}
                <input type="hidden" name="solicitacao_id" value="{{ solicitacao.id }}">
                <button type="submit" class="btn btn-success" name="accept">Aceitar</button>
                <button type="submit" class="btn btn-danger" name="reject">Rejeitar</button>
            </form>
        </div>
    {% empty %}
        <p style="text-align: center; font-size: 1.2rem;">Nenhuma solicitação de amizade pendente.</p>
    {% endfor %}
</div>
{% endblock %}